trigger:
  - develop

variables:
  JVM_ARGS: '-Xms1g -Xmx4g'

parameters:
  - name: generateReport
    default: true
    type: boolean

stages:
  - stage: Client_Side
    pool:
      name:  Karen
    #dependsOn: [] only with enabled subscription
    displayName: PerfTest_Client_Side
    jobs:
      - job: PerfTest
        timeoutInMinutes: 90 # how long to run the job before automatically cancelling
        displayName: PerfTest
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                mkdir reports
                docker run --rm -v $(Build.SourcesDirectory):/mnt/lightohouse -w "/mnt/lightohouse" -v $(Build.SourcesDirectory)/reports:/tmp ibombit/lighthouse-puppeteer-chrome:node16 node $(TEST).js "$(ENV_URL)" $(VUSER) $(PASS)
                ls -la reports
                sudo chmod -R 777 $(Build.SourcesDirectory)
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
              testResultsFiles: 'reports/jmeter.xml'
          - task: PublishPipelineArtifact@1
            displayName: Publish Lighthouse Report
            inputs:
              targetPath: reports
              artifact: lighthouse